spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vetclinic_db
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: INFO
    com.vetclinic: DEBUG
