apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: vetclinic
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DATABASE_URL: "jdbc:postgresql://postgres-service:5432/vetclinic_db"
  DATABASE_USERNAME: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  FRONTEND_URL: "http://a5cd7f33460544019ad9cb2a7cfcc164-505991334.us-east-1.elb.amazonaws.com"
  BACKEND_URL: "http://a41b246d323a84b818dcf01600bb9463-1483797574.us-east-1.elb.amazonaws.com:8081"
  CORS_ORIGINS: "*"
  CLINIC_NAME: "VetClinic Pro"

